name: ci

on:
  push:
    paths:
    - "**/*.py"

jobs:

  core:
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os}}

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - run: pip install .[tests]

    - name: type annotation check
      run: mypy --non-interactive --install-types

    - run: pytest

    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
