name: ci

on:
  push:
    paths:
    - "**/*.py"

jobs:

  core:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
